version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: softka-rabbit
    hostname: my-softka-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"